# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:uponup/JPSpec.git'

target 'MessageBroker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MessageBroker', :path => '../',  :modular_headers => false
#  pod 'MessageBroker', '~> 0.1.5'
  pod "ESPullToRefresh"
  pod 'NotificationBannerSwift', '~> 3.0.0'
  pod 'FMDB', '~> 2.7.5'
  
end
